# Generated by Django 5.1.1 on 2024-10-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0002_alter_addcourse_course_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='section',
        ),
    ]
